### ISSUE TITLE
This project is like elm met hyperapp met purescript

### ISSUE THREAD

**Issue by lukejacksonn** [i-am-tom/purescript-panda#1]
Which is an absolute dynamite combination of philosophies 💥 I'm pretty excited by the prospect of this maturing. It is almost exactly what I have been looking for, to get me trying purescript.

Any further thoughts on the idea or future plans?

Thank you! 🙇

**Comment by i-am-tom** [comment]
Whoa, that's quite a review for a project that doesn't exist yet :D
The idea is really to find out whether we (or, imo, prove that we don't) need a VDOM, and see how that affects our programming. There's a lot to come, so watch this space :)

**Comment by lukejacksonn** [comment]
Sounds like a fun challenge! I will indeed watch this space 🚀 I am very curious to see how purescript can help in this domain. From the little code/spec that is here it looks like you are heading in a good direction anyway.

I will close this issue now 🙃 good luck!
