### ISSUE TITLE
Draw a better panda

### ISSUE THREAD

**Issue by i-am-tom** [i-am-tom/purescript-panda#3]
As can be seen in the README, the current Panda, while cheeky and excellent, isn't an SVG (curse you, Pixelmator). So, if anyone's feeling up for it, it'd be great to have an SVG panda that looks a bit better-designed than this one...

**Comment by Cmdv** [comment]
I'll try finish it tomorrow, needs feet but just realised I took away his stick!!!

<img width="476" alt="screen shot 2018-02-25 at 23 39 26" src="https://user-images.githubusercontent.com/3036557/36647999-31dcf996-1a85-11e8-9b86-c054029137d6.png">

**Comment by Cmdv** [comment]
here you go he can walk unless you want him sat down, I tried to give Panda a PS logo tattoo but it didn't work. I'll PR the svg or email you it? as it won't let you straight upload it in comments.
![screen shot 2018-02-26 at 08 28 38](https://user-images.githubusercontent.com/3036557/36660165-1297209e-1acf-11e8-9fed-988d0b27ae72.png)
ps: if Panda gets backing from google or some other cooperate entity I want 50% as a logo is clearly what makes a framework good!! 😂

**Comment by i-am-tom** [comment]
Damn, @Cmdv. Knocked it out the park. <3
